[workspace]
members = [
  "zomes/grapes",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/guillemcordoba/hc-utils", branch = "hash-eq", package = "hc_utils"}
