---
environment_path: sandbox/wH01rVZ7a0nM1J_VNUj9y
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: sandbox/wH01rVZ7a0nM1J_VNUj9y/keystore
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: ~
